eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      deafultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
   application:
    name: Default
